def on_forever():
    music.play_melody("C C C D E E C C ", 240)
    music.play_melody("E E C C D D D - ", 240)
    music.play_melody("D D D E F F E D ", 240)
    music.play_melody("F F F F F F - - ", 240)
    music.play_melody("E E E F G G E E ", 240)
    music.play_melody("G G E E G G G - ", 240)
    music.play_melody("F F F G A A G F ", 240)
    music.play_melody("A A A A A A - - ", 240)
    music.play_melody("G G G C D E F G ", 240)
    music.play_melody("A A A A A A - - ", 240)
    music.play_melody("A A A D E F G A ", 240)
    music.play_melody("B B B B B B - - ", 240)
    music.play_melody("B B B E F G A B ", 240)
    music.play_melody("C5 C5 C5 C5 C5 - C5 B ", 240)
    music.play_melody("A A F F B B G G ", 240)
    music.play_melody("C5 C5 B A G F E D ", 240)
basic.forever(on_forever)
